# http port set
server:
  port: 8189


# Oracle Connect  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

  # ORM JPA
  jpa:
    hibernate:
      ddl-auto: none # create
    properties:
      hibernate:
        show_sql: true
        format_sql: true 
        
  # gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties: 
      mail:
        smtp:
          auth: true # 인증여부
          starttls.enable: true # starttls : 내부적으로 암호화해서 보냄(스내핑 예방)
         
  # view resolver(Template -> JSP Use)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


# Mybatis
mybatis:     
  # dto Location
  type-aliases-package: com.oracle.oBootMybatis03.model
  # xml Location
  config-location: classpath:configuration.xml # 환경설정
  mapper-locations: classpath:mappers/*.xml
  